version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/home/appuser/app/app
      - ./ee-email1-sa.json:/home/appuser/app/ee-email1-sa.json
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/home/appuser/app/ee-email1-sa.json
      - REDIS_HOST=redis
      - POSTGRES_SERVER=db
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - cv_augmentor_net

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cv_augmentor_net
  
  redis:
    image: redis:7-alpine
    networks:
      - cv_augmentor_net

  worker:
    build: .
    command: celery -A app.worker.celery_app worker --loglevel=info --concurrency=4
    env_file:
      - ./.env
    environment:
      - REDIS_HOST=redis
      - POSTGRES_SERVER=db
    depends_on:
      - redis
      - db
    networks:
      - cv_augmentor_net

volumes:
  postgres_data:

networks:
  cv_augmentor_net:
    driver: bridge